version: '3'
services:
  web:
    build: .
    command: gunicorn scrawl_be.wsgi:application
    ports:
      - "8000:8000"
    expose:
      - "5432"
      - "8000"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: mdillon/postgis
    ports:
      - "5432:5432"
